### ISSUE TITLE
'thread._local' object has no attribute 'pending'

### ISSUE THREAD

**Issue by GregSawin** [theotherp/nzbhydra#413]
After updating to 0.2.159 I've started getting the following error every time I search for something:
'thread._local' object has no attribute 'pending'

I'm running on Win10, searches worked fine before the update from version roughly 0.2.155.  I've restarted nzbhydra several times and tried different searches with and without various indexers.

I'll attach the full log with debugging enabled but this shows the issue:
2016-10-27 14:20:35,289 - INFO - search - Thread-306 - Starting new search: SearchRequest [ type "general", query "test", forbiddenWords "[]", requiredWords "[]", offset "0", loadAll "False", limit "100", indexers "Binsearch" ]
2016-10-27 14:20:35,357 - INFO - search_module - Thread-307 - Binsearch: Starting search
2016-10-27 14:20:36,252 - INFO - binsearch - Thread-307 - Last results count 0
2016-10-27 14:20:36,630 - ERROR - web - Thread-306 - 'thread._local' object has no attribute 'pending'
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "site-packages\flask\app.py", line 1461, in dispatch_request
  File "nzbhydra\web.py", line 339, in wrapped_function
  File "site-packages\webargs\core.py", line 412, in wrapper
  File "nzbhydra\web.py", line 674, in internalapi_search
  File "nzbhydra\web.py", line 635, in startSearch
  File "nzbhydra\search.py", line 307, in search
  File "nzbhydra\search.py", line 433, in search_and_handle_db
  File "site-packages\playhouse\sqliteq.py", line 302, in atomic
AttributeError: 'thread._local' object has no attribute 'pending'

[nzbhydra-debuginfo-2016-10-27-14-22.zip](https://github.com/theotherp/nzbhydra/files/557073/nzbhydra-debuginfo-2016-10-27-14-22.zip)

**Comment by d4k0** [comment]
Same problem here.

**Comment by theotherp** [comment]
Sorry, guys.
